name: github_action_test
on:
  push:
    branches:
      - main
jobs:
  deployjob:
    runs-on: ubuntu-latest

    steps:
      - name: hello_world
        run: echo "hello_world"

      - name: test
        run : |
          echo "Good"
          echo "Morining"

      - name: 깃허브 내장 변수 사용
        run : |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY