name: github_action_test
on:
  push:
    branches:
      - main
jobs:
  deployjob:
    runs-on: ubuntu-latest

    steps:
      - name: hello_world
        run: echo "hello_world"

      - name: test
        run : |
          echo "Good"
          echo "Morining"

      - name: 깃허브 내장 변수 사용
        run : |
          echo "1,  $GITHUB_SHA"
          echo "2,  $GITHUB_REPOSITORY"
          echo "4, $GITHUB_REF_NAME"
          echo "5, $GITHUB_RUN_NUMBER"
          echo "6, $GITHUB_EVENT_NAME"
          echo "7, $GITHUB_OS"
          echo "8, $GITHUB_WORKSPACE"

      - name: 시크릿 변수 사용
        run : |
          echo ${{secrets.MY_SECRET}}
          echo ${{secrets.MY_PAY}}
