name : deploy
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접근
      - uses: appleboy/ssh-action@v1
      - env:
          APPLICATION_PROPERTIES: ${{secrets.APPLICATION_PROPERTIES}}
      - with:
          host : ${{secrets.EC2_HOST}}
          username : ${{secrets.EC2_USERNSMR}}
          key : ${{secrets.EC2_PRIVATE_KEY}}
          envs: APPLICATION_PROPERTIES

          scripts_stop: |
            cd /home/ubuntu/new-repo
            rm -rf src/main/resources/application.yml
            echo $"APPLICATION_PROPERTIES" > src/main/resources/application.yml
            git pull origin main
            ./gradlwe clean build -x test
            sudo fuser -k -n tcp 80 || true
            sudo java -jar build/libs/*SNAPSHOT.jar > ./outout.log 2>&1 &
